// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options } from '@hey-api/client-fetch';
import type { SpecficErrorData, SpecficErrorError, SpecficErrorResponse, DefaultErrorData, DefaultErrorError, DefaultErrorResponse } from './types.gen';

export class TestingService {
    public static specficError(options: Options<SpecficErrorData>) {
        return (options?.client ?? client).post<SpecficErrorResponse, SpecficErrorError>({
            ...options,
            url: '/specific/{id}'
        });
    }
    
    public static defaultError(options: Options<DefaultErrorData>) {
        return (options?.client ?? client).post<DefaultErrorResponse, DefaultErrorError>({
            ...options,
            url: '/default/{id}'
        });
    }
    
}