// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options } from '@hey-api/client-fetch';
import type { DeleteMultipleData, DeleteMultipleError, DeleteMultipleResponse } from './types.gen';

export class TestingService {
    public static deleteMultiple(options: Options<DeleteMultipleData>) {
        return (options?.client ?? client).post<DeleteMultipleResponse, DeleteMultipleError>({
            ...options,
            url: '/demo/{id}'
        });
    }
    
}