// This file is auto-generated by @hey-api/openapi-ts

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    '[key: string]': (unknown | string | number) | undefined;
};

export type SpecficErrorData = {
    path: {
        id: string;
    };
};

export type SpecficErrorResponse = void;

export type SpecficErrorError = ProblemDetails;

export type DefaultErrorData = {
    path: {
        id: string;
    };
};

export type DefaultErrorResponse = void;

export type DefaultErrorError = unknown;

export type $OpenApiTs = {
    '/specific/{id}': {
        post: {
            req: SpecficErrorData;
            res: {
                /**
                 * No Content
                 */
                '204': void;
                /**
                 * Unexpected error
                 */
                '500': ProblemDetails;
            };
        };
    };
    '/default/{id}': {
        post: {
            req: DefaultErrorData;
            res: {
                /**
                 * No Content
                 */
                '204': void;
                /**
                 * Unexpected error
                 */
                default: ProblemDetails;
            };
        };
    };
};